-- Transition Tracker database schema for Supabase/Postgres
-- Run this entire file once in Supabase -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.links (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  destination_url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint links_slug_format check (slug ~ '^[a-z0-9][a-z0-9_-]{0,79}$'),
  constraint links_destination_http check (destination_url ~ '^https?://')
);

create table if not exists public.clicks (
  id bigint generated by default as identity primary key,
  link_id uuid not null references public.links(id) on delete cascade,
  visitor_id text not null,
  referrer text,
  user_agent text,
  clicked_at timestamptz not null default now()
);

create index if not exists clicks_link_id_idx on public.clicks(link_id);
create index if not exists clicks_clicked_at_idx on public.clicks(clicked_at desc);
create index if not exists clicks_visitor_id_idx on public.clicks(visitor_id);

alter table public.links enable row level security;
alter table public.clicks enable row level security;

-- Do not expose tracker data to browser/public roles.
revoke all on table public.links from anon, authenticated;
revoke all on table public.clicks from anon, authenticated;

-- We intentionally create no public RLS policies.
-- The app talks to Supabase only from the server using SUPABASE_SECRET_KEY.

create or replace view public.link_stats
with (security_invoker = true)
as
select
  l.id,
  l.name,
  l.slug,
  l.destination_url,
  l.is_active,
  l.created_at,
  count(c.id)::bigint as clicks,
  count(distinct c.visitor_id)::bigint as unique_visitors,
  max(c.clicked_at) as last_click_at
from public.links l
left join public.clicks c on c.link_id = l.id
group by l.id, l.name, l.slug, l.destination_url, l.is_active, l.created_at;

create or replace view public.overall_stats
with (security_invoker = true)
as
select
  count(*)::bigint as total_clicks,
  count(distinct visitor_id)::bigint as unique_visitors,
  count(*) filter (where clicked_at >= now() - interval '7 days')::bigint as clicks_7d,
  count(*) filter (where clicked_at >= now() - interval '24 hours')::bigint as clicks_24h
from public.clicks;

create or replace view public.daily_stats
with (security_invoker = true)
as
select
  (clicked_at at time zone 'Europe/Kyiv')::date as day,
  count(*)::bigint as clicks
from public.clicks
where clicked_at >= now() - interval '14 days'
group by (clicked_at at time zone 'Europe/Kyiv')::date
order by day asc;

-- Explicit privileges for the server-side service role used by Supabase secret keys.
grant usage on schema public to service_role;
grant all on table public.links to service_role;
grant all on table public.clicks to service_role;
grant usage, select on sequence public.clicks_id_seq to service_role;
grant select on public.link_stats to service_role;
grant select on public.overall_stats to service_role;
grant select on public.daily_stats to service_role;

revoke all on public.link_stats from anon, authenticated;
revoke all on public.overall_stats from anon, authenticated;
revoke all on public.daily_stats from anon, authenticated;
