-- TrackLink database schema for Supabase/Postgres
-- Safe to run again when upgrading an existing TrackLink database.
-- Current schema target: TrackLink v0.4.1

create extension if not exists pgcrypto;

create table if not exists public.link_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  background_color text not null default '#e8eef7',
  created_at timestamptz not null default now(),
  constraint link_groups_name_length check (char_length(name) between 1 and 80)
);

create table if not exists public.links (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  destination_url text not null,
  group_id uuid references public.link_groups(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint links_slug_format check (slug ~ '^[a-z0-9][a-z0-9_-]{0,79}$'),
  constraint links_destination_http check (destination_url ~ '^https?://')
);

create table if not exists public.clicks (
  id bigint generated by default as identity primary key,
  link_id uuid not null references public.links(id) on delete cascade,
  visitor_id text not null,
  country_code text,
  user_agent text,
  clicked_at timestamptz not null default now()
);

-- Upgrade existing installations.
alter table public.links
  add column if not exists group_id uuid references public.link_groups(id) on delete set null;
alter table public.link_groups add column if not exists background_color text;
update public.link_groups set background_color = '#e8eef7' where background_color is null or btrim(background_color) = '';
alter table public.link_groups alter column background_color set default '#e8eef7';
alter table public.link_groups alter column background_color set not null;
alter table public.clicks add column if not exists country_code text;
alter table public.clicks drop column if exists referrer;

create index if not exists links_group_id_idx on public.links(group_id);
create index if not exists clicks_link_id_idx on public.clicks(link_id);
create index if not exists clicks_clicked_at_idx on public.clicks(clicked_at desc);
create index if not exists clicks_visitor_id_idx on public.clicks(visitor_id);
create index if not exists clicks_link_clicked_at_idx on public.clicks(link_id, clicked_at desc);
create index if not exists clicks_country_code_idx on public.clicks(country_code);

alter table public.link_groups enable row level security;
alter table public.links enable row level security;
alter table public.clicks enable row level security;

-- Do not expose tracker data to browser/public roles.
revoke all on table public.link_groups from anon, authenticated;
revoke all on table public.links from anon, authenticated;
revoke all on table public.clicks from anon, authenticated;

-- The application accesses Supabase only from server-side code with a Secret key.

create or replace view public.link_stats
with (security_invoker = true)
as
select
  l.id,
  l.name,
  l.slug,
  l.destination_url,
  l.is_active,
  l.created_at,
  count(c.id)::bigint as clicks,
  count(distinct c.visitor_id)::bigint as unique_visitors,
  max(c.clicked_at) as last_click_at,
  count(c.id) filter (
    where (c.clicked_at at time zone 'Europe/Kyiv')::date =
      (now() at time zone 'Europe/Kyiv')::date
  )::bigint as today_clicks,
  count(distinct c.visitor_id) filter (
    where (c.clicked_at at time zone 'Europe/Kyiv')::date =
      (now() at time zone 'Europe/Kyiv')::date
  )::bigint as today_unique,
  count(c.id) filter (
    where (c.clicked_at at time zone 'Europe/Kyiv')::date >=
      (now() at time zone 'Europe/Kyiv')::date - 6
  )::bigint as clicks_7d,
  count(distinct c.visitor_id) filter (
    where (c.clicked_at at time zone 'Europe/Kyiv')::date >=
      (now() at time zone 'Europe/Kyiv')::date - 6
  )::bigint as unique_7d,
  count(c.id) filter (
    where date_trunc('month', c.clicked_at at time zone 'Europe/Kyiv') =
      date_trunc('month', now() at time zone 'Europe/Kyiv')
  )::bigint as month_clicks,
  count(distinct c.visitor_id) filter (
    where date_trunc('month', c.clicked_at at time zone 'Europe/Kyiv') =
      date_trunc('month', now() at time zone 'Europe/Kyiv')
  )::bigint as month_unique,
  l.group_id,
  g.name as group_name
from public.links l
left join public.link_groups g on g.id = l.group_id
left join public.clicks c on c.link_id = l.id
group by l.id, l.name, l.slug, l.destination_url, l.is_active, l.created_at, l.group_id, g.name;

-- Existing first four columns are kept for backward compatibility.
create or replace view public.overall_stats
with (security_invoker = true)
as
select
  count(*)::bigint as total_clicks,
  count(distinct visitor_id)::bigint as unique_visitors,
  count(*) filter (
    where (clicked_at at time zone 'Europe/Kyiv')::date >=
      (now() at time zone 'Europe/Kyiv')::date - 6
  )::bigint as clicks_7d,
  count(*) filter (where clicked_at >= now() - interval '24 hours')::bigint as clicks_24h,
  count(distinct visitor_id) filter (
    where (clicked_at at time zone 'Europe/Kyiv')::date >=
      (now() at time zone 'Europe/Kyiv')::date - 6
  )::bigint as unique_7d,
  count(*) filter (
    where (clicked_at at time zone 'Europe/Kyiv')::date =
      (now() at time zone 'Europe/Kyiv')::date
  )::bigint as today_clicks,
  count(distinct visitor_id) filter (
    where (clicked_at at time zone 'Europe/Kyiv')::date =
      (now() at time zone 'Europe/Kyiv')::date
  )::bigint as today_unique,
  count(*) filter (
    where date_trunc('month', clicked_at at time zone 'Europe/Kyiv') =
      date_trunc('month', now() at time zone 'Europe/Kyiv')
  )::bigint as month_clicks,
  count(distinct visitor_id) filter (
    where date_trunc('month', clicked_at at time zone 'Europe/Kyiv') =
      date_trunc('month', now() at time zone 'Europe/Kyiv')
  )::bigint as month_unique
from public.clicks;

create or replace view public.daily_stats
with (security_invoker = true)
as
select
  (clicked_at at time zone 'Europe/Kyiv')::date as day,
  count(*)::bigint as clicks
from public.clicks
where clicked_at >= now() - interval '14 days'
group by (clicked_at at time zone 'Europe/Kyiv')::date
order by day asc;

create or replace view public.click_records
with (security_invoker = true)
as
select
  c.id,
  c.link_id,
  l.name as link_name,
  l.slug,
  l.destination_url,
  c.visitor_id,
  c.country_code,
  c.user_agent,
  c.clicked_at,
  (c.clicked_at at time zone 'Europe/Kyiv')::date as local_day,
  l.group_id,
  g.name as group_name
from public.clicks c
join public.links l on l.id = c.link_id
left join public.link_groups g on g.id = l.group_id;

grant usage on schema public to service_role;
grant all on table public.link_groups to service_role;
grant all on table public.links to service_role;
grant all on table public.clicks to service_role;
grant usage, select on sequence public.clicks_id_seq to service_role;
grant select on public.link_stats to service_role;
grant select on public.overall_stats to service_role;
grant select on public.daily_stats to service_role;
grant select on public.click_records to service_role;

revoke all on public.link_stats from anon, authenticated;
revoke all on public.overall_stats from anon, authenticated;
revoke all on public.daily_stats from anon, authenticated;
revoke all on public.click_records from anon, authenticated;
